### PR TITLE
Handle ns attr-map [#50]

### LINKED ISSUE #50: Support attr-map in ns form
An ns form like:

```
(ns foo.bar
   {:baz "baz"})
```
results in the file being skipped with:
`clojure.lang.ExceptionInfo: Unknown ns node form :map`

The attr-map is an alternate way to specify metadata for the ns. 

I started implementing this, but got stuck on how to correctly transform a node that represents the map. I'm happy to keep working on it, but could use some guidance.

### PR DESCRIPTION
**Pull request by tobias**
This is my attempt to resolve #50. It's not yet correct, since the indentation for the map is wrong (the failing test is testing for what I believe should be the correct format), but I wanted to put up what I had so far for discussion.

This currently formats:

```
(ns foo
      {:foo :bar 
   :baz true})
```

As: 

```
(ns foo
  {:foo :bar 
 :baz true})
```

Instead of:

```
(ns foo
  {:foo :bar 
   :baz true})
```

What do I need to change to have this format correctly?

### CODE REVIEW

File: src/cljstyle/format/ns.clj [hunk 1]
```diff
@@ -1,5 +1,6 @@
 (ns cljstyle.format.ns
   (:require
+    [cljstyle.format.indent :as indent]
```
Comment (greglook) [inline src/cljstyle/format/ns.clj:3]: You shouldn't need to pull in the indent logic here; that's a different formatting rule and they shouldn't be coupled. Indentation composes with other rules by running _after_ the other logic has had a chance to rewrite things, insert line breaks, and so on.

File: src/cljstyle/format/ns.clj [hunk 2]
```diff
@@ -385,6 +390,13 @@
     [(n/spaces indent-size) docstr]))
 
 
+(defn- render-attr-map
+  "Render ns data provided as an attr-map."
+  [opts attr-map]
+  (when attr-map
+    [(n/spaces indent-size) (indent/reindent attr-map opts)]))
```
Comment (greglook) [inline src/cljstyle/format/ns.clj:397]: This doesn't work the way you want because `reindent` here doesn't have the context on the rest of the ns form. Instead, you could manually format the map entries with a basic `(n/spaces (inc indent-size))` interposed. This wouldn't fix everything but I think the indentation logic might catch the rest.

Comment (tobias) [reply src/cljstyle/format/ns.clj]: Thanks for the feedback @greglook! I just force pushed a new implementation that now passes the (expanded) test. Let me know if you would like any other changes.

**Comment by greglook** [comment]
I was hoping to get a few more features and issues resolved before the next release, but I'll get something out by the end of the week.

**Comment by tobias** [comment]
Thanks Greg!
